name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    uses: actions/checkout@v2
    - name: build
      run: gcc MasterCalc.c -o MasterCalc.exe
    - name: Run
      run: ./MasterCalc.exe
